---
name: "Base theme"
author: "REZO ZERO"
copyright: "REZO ZERO"
themeDir: "BaseTheme"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "0.8.1"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes:
        - "Resources/import/nodetype/Page.rzt"
    tags: []
    nodes:
        - "Resources/import/node/node.rzn"
