---
name: "RZ Base theme"
author: "REZO ZERO"
copyright: "REZO ZERO"
themeDir: "BaseTheme"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "0.6.0"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes: []
    tags: []
    nodes: []
