---
name: "Base theme"
author: "Rezo Zero"
copyright: "Rezo Zero"
themeDir: "BaseTheme"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "0.16.0"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes:
        - "Resources/import/node-type/Neutral.rzt"
        - "Resources/import/node-type/Page.rzt"
    tags: []
    nodes:
        - "Resources/import/node/node-main-menu.rzn"
